description: "This bot automatically repost x.com and twitter.com posts as fxtwitter ones."
version: "3.2.7"
color: 0x1d9bf0
hot_reload: false
about_command: true
analytic: true

log:
  file: "log.txt"
  alert_user: false
  stream_to_err: false
  date_format: "%d/%m/%Y %H:%M:%S"
  format: "[{asctime}] {levelformat} {name:<20} {message}"

emoji:
  github: "ðŸ–¥ï¸"
  add: "âž•"
  discord: "ðŸ’¬"
  twitter: "ðŸ¦"
  instagram: "ðŸ“¸"
  tiktok: "ðŸŽ¶"
  reddit: "ðŸ¤–"
  threads: "ðŸ§µ"
  snapchat: "ðŸ‘»"
  facebook: "ðŸ“˜"
  bluesky: "ðŸ¦‹"
  pixiv: "ðŸ–¼ï¸"
  mastodon: "ðŸ˜"
  tumblr: "ðŸ“"
  deviantart: "ðŸŽ¨"
  twitch: "ðŸŽ®"
  spotify: "ðŸŽµ"
  bilibili: "ðŸ“º"
  ifunny: "ðŸ™‚"
  furaffinity: "ðŸ¾"
  youtube: "ðŸ“º"
  reply: "â†©ï¸"
  webhooks: "ðŸ”„"
  x: "âŽ"
  fixtweet: "ðŸ¤–"
  role: "ðŸŽ­"

invite_link: "https://discord.com/oauth2/authorize?client_id={id}"
repo_link: "https://github.com/Kyrela/FixTweetBot"
support_link: "https://discord.gg/3ej9JrkF3U"
